### ISSUE TITLE
Task -- Scrape Seeking Alpha Trending Articles

### ISSUE THREAD

**Issue by abpwrs** [abpwrs/thee-flying-chicken#5]
Using scrapy, scrape the content off of each of the trending articles on [seeking alpha](https://seekingalpha.com/).     

<img width="655" alt="screenshot 2018-12-17 17 30 05" src="https://user-images.githubusercontent.com/40620013/50122306-731d7f00-0221-11e9-8ea3-7a5e0860dc73.png">

Store these articles as JSON files, so that the will be easy to transfer over to mongodb.

**Comment by dragonairbender** [comment]
I think I got it

**Comment by dragonairbender** [comment]
What should I do with my scrapy code?

**Comment by abpwrs** [comment]
Do you know how to make a pull request?

**Comment by abpwrs** [comment]
if you made your changes on master, 
you'll want to create a new branch
```bash
git checkout -b DC_branch
```
and then push that branch to a new remote branch
```bash
git push -u origin DC_branch
```
then on our repository github, you should be able to go to the pull request tab (on this github repo) and select your feature branch (DC_branch) and start a pull request

**Comment by dragonairbender** [comment]
Umm i think that did it. I'm still kind of confused with github

**Comment by abpwrs** [comment]
So there was an issue with your code not sharing a git history with the rest of the project. I put the code into a new PR(pull request). We can talk about the code in the PR discussion

**Comment by abpwrs** [comment]
Closing after PR7 Seeking Alpha Spider
