### ISSUE TITLE
Task -- Evaluate Stock Market APIs

### ISSUE THREAD

**Issue by abpwrs** [abpwrs/thee-flying-chicken#6]
I think we will want to use Alpaca, but we should look at Alpha Vantage too.     
For both Alpaca and Alpha Vantage we will need to do the following.     
- [ ] Set up API keys    
(do not post these publicly or add them to github, we will setup a system to share these) 
- [ ] Make requests for Google, Facebook and whatever other companies you want
- [ ] Visualize this data using [matplotlib](https://matplotlib.org/) and [pandas](https://pandas.pydata.org/)       
some [reference code](https://gist.github.com/abpwrs/91ed537e0cd4821aba0dcd65451e284e)    
 [pandas crash course](https://pandas.pydata.org/pandas-docs/stable/10min.html) and [matplotlib crash course](https://pythonprogramming.net/matplotlib-python-3-basics-tutorial/)

- [ ]  make notes on ease of use and valuable functionality we may want

**Comment by dragonairbender** [comment]
I went through and read a few tutorials but I am not sure what to do with this information
